api/CHANGELOG.md, api/api/v3/auth/README.md
Adding some a few errors, let's check before merging
=> [Auth] Feat : Add some errors

CONTRIBUTING.md
- Add the **commit** guidelines
- Add the **issue titles** guidelines
- Add the **PR titles** guidelines
=> [Overall] Update : Clearer contributing guidelines 

api/api/v3/README.md, api/api/v3/cars/README.md, api/api/v3/cars/locations-geojson.md, api/api/v3/trips/README.md, api/api/v3/trips/locations-geojson.md
- Add the `geojson` locations routes (trips and cars) to the `README.md`s
=> [Docs] Locations : Add geojson routes to the indexes

README.md, api/CHANGELOG.md, api/README.md, api/api/v3/README.md, api/api/v3/cars/car_id.md, api/api/v3/cars/locations-geojson.md, api/api/v3/cars/locations.md, api/api/v3/cars/signals.md, api/api/v3/cars/status.md, api/api/v3/cars/trips.md, api/api/v3/trips/locations-geojson.md, api/api/v3/trips/locations.md, api/api/v3/trips/signals.md, api/api/v3/trips/trip_id.md, api/api/v3/users/cars.md, api/api/v3/users/user_id.md
- Add the description of the *sandbox* mode in READMEs
- Add the sandbox `env` in each route affected
=> Fixes #17 : [Overall] All : Add a sandbox API

api/CHANGELOG.md, api/api/v3/README.md, api/api/v3/cars/README.md, api/api/v3/cars/stats/mileage.md, api/api/v3/cars/stats/usedtime.md
Add documentation for 
- `mileage`
- `usedtime`
end points under `cars`
=> [Cars] stats : Add statistics endpoints

api/api/v3/auth/auth.md, setup/README.md
=> Fixes #28 : Small typo in setup/README.md and auth/auth.md

api/CHANGELOG.md, api/api/v3/cars/stats/usedtime.md
Fixes typo in [api/api/v3/cars/stats/usedtime.md](api/api/v3/cars/stats/usedtime.md)
=> [Typo] in used_time

api/CHANGELOG.md, api/api/v3/README.md
- Fixes typo
- Updated changelog
=> Fixes #26 : [Typo] in xee-api-docs/api/api/v3/README.md

api/CHANGELOG.md, api/README.md, api/compat/v1/README.md, api/compat/v1/cardb/README.md, api/compat/v1/cardb/cardbId.md, api/compat/v1/ktype/README.md, api/compat/v1/ktype/ktype.md
Add compat API with 2 new endpoints
- cardb
- ktype
*The compat API is used to know which signal is available on which car.*
=> [API] Add compat API

api/CHANGELOG.md, api/compat/v1/ktype/ktype.md
The parameter `inservice` was replaced by `in_service`
See #36
=> Fixes #36 [Compat] : Modify parameter

api/CHANGELOG.md, api/api/v3/README.md, api/api/v3/trips/README.md, api/api/v3/trips/trip_id/stats.md, api/api/v3/trips/trip_id/stats/mileage.md, api/api/v3/trips/trip_id/stats/usedtime.md
- Add `trips/{tripId}/stats`
- Add `trips/{tripId}/stats/usedtime`
- Add `trips/{tripId}/stats/mileage`
- Update `CHANGELOG`
=> Fixes #40 [Trip] Stats : Add trip statistics

api/CHANGELOG.md, api/api/v3/cars/signals_list.md
- Update the list of standard signals
- Add the list of advanced signals
- Values are clearer
=> Fixes #43 : [Signals] Typo in list of signals

api/CHANGELOG.md, api/api/v3/users/me/cars.md
As we're accessing cars through me, the user errors are not possible.
=> [DOC] users/me/cars : Remove unpossible errors

api/CHANGELOG.md, api/api/v3/cars/signals_list.md
* Add the signal to the list of default signals
=> [Signals] Add the ComputedFuelLevel

api/api/v3/cars/trips.md, api/api/v3/trips/trip_id.md
=> Fixes #34 - [Trips] trips : remove creationDate and lastUpdateDate from documentation

api/api/v3/cars/signals_list.md
Used to make copy/paste for translation :)
=> [Doc] Signal list : Typo Accord like other

api/api/v3/cars/car_id.md, api/api/v3/cars/locations-geojson.md, api/api/v3/cars/locations.md, api/api/v3/cars/signals.md, api/api/v3/cars/stats/mileage.md, api/api/v3/cars/stats/usedtime.md, api/api/v3/cars/status.md, api/api/v3/cars/trips.md, api/api/v3/trips/trip_id/stats.md, api/api/v3/trips/trip_id/stats/mileage.md, api/api/v3/trips/trip_id/stats/usedtime.md, api/api/v3/users/README.md, api/api/v3/users/cars.md, api/api/v3/users/cars_create.md, api/api/v3/users/me.md, api/api/v3/users/me/cars.md, api/api/v3/users/user_id.md
=> car creation

api/api/v3/devices/README.md, api/api/v3/devices/associate_car.md, api/api/v3/devices/associate_user.md, api/api/v3/devices/dissociate.md
=> fix(typo): change xeeId to deviceId

README.md
Xee API is reliable, I agree, but ...
... just in case !
=> [docs] add status badges + link to status.xee.com

api/compat/v1/README.md, api/compat/v1/cardb/README.md, api/compat/v1/cardb/cardbId.md, api/compat/v1/ktype/README.md, api/compat/v1/ktype/ktype.md, api/compat/v3/README.md, api/compat/v3/brands.md, api/compat/v3/cardb.md, api/compat/v3/ktype.md, api/compat/v3/models.md, api/compat/v3/versions.md
=> New compat API
